import "./globals.css";
import Link from 'next/link'
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Header</h1>
          <nav>
            <ul>
              <li><Link href="/managerdashboard">manager</Link></li>
            </ul>
            <ul>
              <li><Link href="/workerdashboard">worker</Link></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
