# version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
